services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: finmate
      POSTGRES_PASSWORD: finmate
      POSTGRES_DB: finmate
    ports:
      - "5432:5432"
    volumes:
      - finmate_pg:/var/lib/postgresql/data

volumes:
  finmate_pg:
